import { useCallback, useEffect, useMemo, useState } from 'react';
import { api } from './api';

const icon = (name, size = 18) => {
  const paths = {
    grid: <><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>,
    board: <><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M9 4v16M15 4v16"/></>,
    plus: <><path d="M12 5v14M5 12h14"/></>,
    search: <><circle cx="11" cy="11" r="6.5"/><path d="m16 16 4 4"/></>,
    bell: <><path d="M18 9a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></>,
    settings: <><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.33 2.33-.06-.06a1.7 1.7 0 0 0-1.88-.34 1.7 1.7 0 0 0-1.03 1.56v.08h-3.3v-.08a1.7 1.7 0 0 0-1.03-1.56 1.7 1.7 0 0 0-1.88.34l-.06.06-2.33-2.33.06-.06A1.7 1.7 0 0 0 6.3 15a1.7 1.7 0 0 0-1.56-1.03h-.08v-3.3h.08A1.7 1.7 0 0 0 6.3 9.64a1.7 1.7 0 0 0-.34-1.88L5.9 7.7l2.33-2.33.06.06a1.7 1.7 0 0 0 1.88.34 1.7 1.7 0 0 0 1.03-1.56v-.08h3.3v.08a1.7 1.7 0 0 0 1.03 1.56 1.7 1.7 0 0 0 1.88-.34l.06-.06L19.8 7.7l-.06.06a1.7 1.7 0 0 0-.34 1.88 1.7 1.7 0 0 0 1.56 1.03h.08v3.3h-.08A1.7 1.7 0 0 0 19.4 15Z"/></>,
    chevron: <path d="m6 9 6 6 6-6"/>, close: <><path d="m6 6 12 12M18 6 6 18"/></>,
    logout: <><path d="M10 17l5-5-5-5M15 12H3"/><path d="M21 19V5a2 2 0 0 0-2-2h-5"/></>,
    comment: <path d="M20 15a3 3 0 0 1-3 3H9l-5 3v-3a3 3 0 0 1-2-3V7a3 3 0 0 1 3-3h12a3 3 0 0 1 3 3Z"/>,
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>;
};

const getInitials = (name = '') => name.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase() || '?';
const dateLabel = (date) => new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric' }).format(new Date(date));

function Auth({ onAuth }) {
  const [mode, setMode] = useState('login');
  const [form, setForm] = useState({ name: '', email: '', password: '', role: 'user' });
  const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const submit = async (event) => {
    event.preventDefault(); setError(''); setLoading(true);
    try {
      const data = await api(`/users/${mode === 'login' ? 'login' : 'register'}`, { method: 'POST', body: JSON.stringify(mode === 'login' ? { email: form.email, password: form.password } : form) });
      onAuth(data);
    } catch (err) { setError(err.message); } finally { setLoading(false); }
  };
  return <main className="auth-page"><section className="auth-intro"><div className="brand"><span className="brand-mark">J</span>SastaJira</div><div><p className="eyebrow">LIGHTWEIGHT PROJECT MANAGEMENT</p><h1>Make every piece<br/>of work count.</h1><p className="intro-copy">A calmer place for your team to plan, track, and ship meaningful work together.</p></div><div className="auth-orb orb-one"/><div className="auth-orb orb-two"/></section><section className="auth-panel"><form className="auth-card" onSubmit={submit}><div className="mobile-brand"><span className="brand-mark">J</span>SastaJira</div><p className="eyebrow">WELCOME BACK</p><h2>{mode === 'login' ? 'Sign in to your workspace' : 'Create your workspace account'}</h2>{error && <p className="form-error">{error}</p>}{mode === 'register' && <label>Full name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Aarav Sharma" /></label>}<label>Email address<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="you@company.com" /></label><label>Password<input required minLength="6" type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} placeholder="At least 6 characters" /></label>{mode === 'register' && <label>Role<select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })}><option value="user">Team member</option><option value="manager">Manager</option><option value="admin">Admin</option></select></label>}<button className="primary wide" disabled={loading}>{loading ? 'Please wait…' : mode === 'login' ? 'Sign in' : 'Create account'}</button><p className="switch-auth">{mode === 'login' ? 'New to SastaJira?' : 'Already have an account?'} <button type="button" onClick={() => { setMode(mode === 'login' ? 'register' : 'login'); setError(''); }}>{mode === 'login' ? 'Create an account' : 'Sign in'}</button></p></form></section></main>;
}

function Sidebar({ user, active, setActive, onCreate, onLogout }) {
  return <aside className="sidebar"><div className="brand"><span className="brand-mark">J</span>SastaJira</div><button className="create-button" onClick={onCreate}>{icon('plus')} Create ticket <kbd>C</kbd></button><nav><p className="nav-heading">WORKSPACE</p><button className={active === 'dashboard' ? 'nav-item active' : 'nav-item'} onClick={() => setActive('dashboard')}>{icon('grid')} Overview</button><button className={active === 'board' ? 'nav-item active' : 'nav-item'} onClick={() => setActive('board')}>{icon('board')} My board</button></nav><div className="sidebar-bottom"><button className="nav-item">{icon('settings')} Settings</button><div className="user-card"><span className="avatar purple">{getInitials(user.name)}</span><div><strong>{user.name}</strong><small>{user.role}</small></div><button aria-label="Log out" onClick={onLogout}>{icon('logout', 16)}</button></div></div></aside>;
}

function TicketCard({ ticket, onOpen, compact = false }) {
  const assignee = ticket.assignee; const priority = ticket.priority || 'medium';
  return <button className={`ticket-card ${compact ? 'compact' : ''}`} onClick={() => onOpen(ticket._id)}><div className="ticket-top"><span className={`priority-dot ${priority}`}/><span className="ticket-key">SJ-{ticket._id.slice(-4).toUpperCase()}</span><span className={`status-pill ${ticket.status.replace(' ', '-')}`}>{ticket.status}</span></div><strong>{ticket.title}</strong>{!compact && <p>{ticket.description}</p>}<div className="ticket-meta"><span className="avatar small">{assignee ? getInitials(assignee.name) : '—'}</span><span>{assignee?.name || 'Unassigned'}</span><span className="comment-count">{icon('comment', 14)} {ticket.comments?.length || 0}</span></div></button>;
}

function Dashboard({ tickets, onOpen, onCreate, setActive }) {
  const metrics = [['Open', tickets.filter((t) => t.status === 'open').length, 'blue'], ['In progress', tickets.filter((t) => t.status === 'in progress').length, 'amber'], ['Closed', tickets.filter((t) => t.status === 'closed').length, 'green']];
  const recent = [...tickets].sort((a, b) => new Date(b.updatedAt) - new Date(a.updatedAt)).slice(0, 5);
  return <><div className="page-heading"><div><p className="eyebrow">YOUR WORKSPACE</p><h1>Good morning 👋</h1><p className="muted">Here’s what’s moving across your team.</p></div><button className="primary" onClick={onCreate}>{icon('plus')} New ticket</button></div><section className="metrics">{metrics.map(([label, value, color]) => <div className="metric" key={label}><span className={`metric-icon ${color}`}>{value}</span><div><p>{label}</p><strong>{value} <small>tickets</small></strong></div></div>)}<div className="metric total"><span className="metric-icon navy">{tickets.length}</span><div><p>Total work</p><strong>{tickets.length} <small>tickets</small></strong></div></div></section><section className="overview-grid"><div className="section-card activity"><div className="section-title"><div><p className="eyebrow">LATEST UPDATES</p><h2>Recent activity</h2></div><button className="text-button" onClick={() => setActive('board')}>View board →</button></div>{recent.length ? <div className="activity-list">{recent.map((ticket) => <button key={ticket._id} className="activity-row" onClick={() => onOpen(ticket._id)}><span className="avatar small blue-avatar">{getInitials(ticket.reporter?.name)}</span><span><strong>{ticket.reporter?.name || 'Team member'}</strong> updated <b>{ticket.title}</b><small>{dateLabel(ticket.updatedAt)}</small></span><span className={`status-pill ${ticket.status.replace(' ', '-')}`}>{ticket.status}</span></button>)}</div> : <Empty onCreate={onCreate}/>}</div><div className="section-card focus"><p className="eyebrow">TEAM FOCUS</p><h2>Keep work flowing.</h2><p>Start by adding your first ticket, then move it through your board as work progresses.</p><button className="secondary" onClick={onCreate}>Create your first ticket</button></div></section></>;
}

function Board({ tickets, onOpen, onCreate }) { const columns = [['open', 'To do'], ['in progress', 'In progress'], ['closed', 'Done']]; return <><div className="page-heading"><div><p className="eyebrow">WORK MANAGEMENT</p><h1>My board</h1><p className="muted">Drag work forward by updating its status.</p></div><button className="primary" onClick={onCreate}>{icon('plus')} New ticket</button></div><div className="board">{columns.map(([status, title]) => <section className="board-column" key={status}><div className="column-heading"><h2>{title}</h2><span>{tickets.filter((t) => t.status === status).length}</span></div><div className="ticket-stack">{tickets.filter((t) => t.status === status).map((ticket) => <TicketCard key={ticket._id} ticket={ticket} onOpen={onOpen} compact/>)}{!tickets.some((t) => t.status === status) && <p className="empty-column">Nothing here yet</p>}</div></section>)}</div></> }
function Empty({ onCreate }) { return <div className="empty"><div>✦</div><h3>No tickets yet</h3><p>Start organising your team’s work in one place.</p><button className="primary" onClick={onCreate}>{icon('plus')} Create ticket</button></div> }

function TicketModal({ id, user, users, onClose, onChanged }) {
  const [ticket, setTicket] = useState(null); const [comment, setComment] = useState(''); const [editing, setEditing] = useState(false); const [form, setForm] = useState({}); const [error, setError] = useState('');
  const load = useCallback(async () => { try { const data = await api(`/tickets/${id}`); setTicket(data); setForm({ title: data.title, description: data.description, status: data.status, priority: data.priority, assignee: data.assignee?._id || '' }); } catch (err) { setError(err.message); } }, [id]);
  useEffect(() => { load(); }, [load]);
  if (!ticket) return <Modal onClose={onClose}><div className="loading">{error || 'Loading ticket…'}</div></Modal>;
  const canEdit = user.role === 'admin' || ticket.reporter?._id === user.id || ticket.assignee?._id === user.id;
  const save = async (e) => { e.preventDefault(); try { await api(`/tickets/${id}`, { method: 'PUT', body: JSON.stringify({ ...form, assignee: form.assignee || undefined }) }); await load(); await onChanged(); setEditing(false); } catch (err) { setError(err.message); } };
  const addComment = async (e) => { e.preventDefault(); if (!comment.trim()) return; try { await api(`/comments/tickets/${id}/comments`, { method: 'POST', body: JSON.stringify({ text: comment }) }); setComment(''); await load(); await onChanged(); } catch (err) { setError(err.message); } };
  return <Modal onClose={onClose}><div className="modal-ticket"><div className="modal-header"><div><span className="ticket-key">TICKET · SJ-{ticket._id.slice(-4).toUpperCase()}</span><h2>{ticket.title}</h2></div><button className="icon-button" onClick={onClose}>{icon('close')}</button></div>{error && <p className="form-error">{error}</p>}{editing ? <form className="ticket-form" onSubmit={save}><label>Title<input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })}/></label><label>Description<textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })}/></label><div className="form-row"><label>Status<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}><option value="open">To do</option><option value="in progress">In progress</option><option value="closed">Done</option></select></label><label>Priority<select value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label></div>{users.length > 0 && <label>Assignee<select value={form.assignee} onChange={(e) => setForm({ ...form, assignee: e.target.value })}><option value="">Unassigned</option>{users.map((person) => <option key={person._id} value={person._id}>{person.name}</option>)}</select></label>}<div className="form-actions"><button type="button" className="secondary" onClick={() => setEditing(false)}>Cancel</button><button className="primary">Save changes</button></div></form> : <><div className="ticket-content"><p>{ticket.description}</p><aside className="details"><div><small>STATUS</small><span className={`status-pill ${ticket.status.replace(' ', '-')}`}>{ticket.status}</span></div><div><small>PRIORITY</small><span className={`priority-text ${ticket.priority}`}>● {ticket.priority}</span></div><div><small>ASSIGNEE</small><span>{ticket.assignee?.name || 'Unassigned'}</span></div><div><small>REPORTER</small><span>{ticket.reporter?.name || '—'}</span></div></aside></div>{canEdit && <button className="secondary" onClick={() => setEditing(true)}>Edit ticket</button>}</>}<div className="comments"><h3>Activity <span>{ticket.comments?.length || 0}</span></h3>{ticket.comments?.map((item) => <div className="comment" key={item._id}><span className="avatar small blue-avatar">{getInitials(item.author?.name)}</span><div><strong>{item.author?.name || 'Unknown'}</strong><small>{dateLabel(item.createdAt)}</small><p>{item.text}</p></div></div>)}<form className="comment-form" onSubmit={addComment}><span className="avatar small purple">{getInitials(user.name)}</span><input value={comment} onChange={(e) => setComment(e.target.value)} placeholder="Write a comment…"/><button className="primary">Send</button></form></div></div></Modal>;
}

function CreateModal({ users, onClose, onCreated }) { const [form, setForm] = useState({ title: '', description: '', priority: 'medium', assignee: '' }); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const submit = async (e) => { e.preventDefault(); setSaving(true); try { await api('/tickets/create', { method: 'POST', body: JSON.stringify({ ...form, assignee: form.assignee || undefined }) }); await onCreated(); onClose(); } catch (err) { setError(err.message); } finally { setSaving(false); } }; return <Modal onClose={onClose}><div className="modal-ticket"><div className="modal-header"><div><p className="eyebrow">NEW WORK ITEM</p><h2>Create a ticket</h2></div><button className="icon-button" onClick={onClose}>{icon('close')}</button></div><form className="ticket-form" onSubmit={submit}>{error && <p className="form-error">{error}</p>}<label>Title<input required autoFocus value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="What needs to be done?"/></label><label>Description<textarea required value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} placeholder="Add context so the right person can pick this up…"/></label><div className="form-row"><label>Priority<select value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label>{users.length > 0 && <label>Assignee<select value={form.assignee} onChange={(e) => setForm({ ...form, assignee: e.target.value })}><option value="">Unassigned</option>{users.map((person) => <option key={person._id} value={person._id}>{person.name}</option>)}</select></label>}</div><div className="form-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={saving}>{saving ? 'Creating…' : 'Create ticket'}</button></div></form></div></Modal> }
function Modal({ children, onClose }) { useEffect(() => { const close = (e) => e.key === 'Escape' && onClose(); window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, [onClose]); return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal" onMouseDown={(e) => e.stopPropagation()}>{children}</div></div> }

export default function App() {
  const [auth, setAuth] = useState(() => { try { return JSON.parse(localStorage.getItem('sastajira_user')); } catch { return null; } }); const [tickets, setTickets] = useState([]); const [users, setUsers] = useState([]); const [active, setActive] = useState('dashboard'); const [modal, setModal] = useState(null); const [loading, setLoading] = useState(true); const [query, setQuery] = useState(''); const [error, setError] = useState('');
  const refresh = useCallback(async () => { if (!auth) return; try { setError(''); const data = await api('/tickets'); setTickets(data); if (auth.user.role === 'manager') setUsers(await api('/users/get')); } catch (err) { setError(err.message); if (/token|authorization/i.test(err.message)) logout(); } finally { setLoading(false); } }, [auth]);
  useEffect(() => { refresh(); }, [refresh]);
  const completeAuth = (data) => { localStorage.setItem('sastajira_token', data.token); localStorage.setItem('sastajira_user', JSON.stringify(data)); setAuth(data); };
  const logout = () => { localStorage.removeItem('sastajira_token'); localStorage.removeItem('sastajira_user'); setAuth(null); setTickets([]); };
  const filtered = useMemo(() => tickets.filter((ticket) => `${ticket.title} ${ticket.description}`.toLowerCase().includes(query.toLowerCase())), [tickets, query]);
  if (!auth) return <Auth onAuth={completeAuth}/>;
  return <div className="app-shell"><Sidebar user={auth.user} active={active} setActive={setActive} onCreate={() => setModal({ type: 'create' })} onLogout={logout}/><main className="main"><header className="topbar"><div className="breadcrumbs">Workspace <span>/</span> {active === 'dashboard' ? 'Overview' : 'My board'}</div><div className="topbar-actions"><label className="search">{icon('search')}<input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search tickets…"/></label><button className="icon-button">{icon('bell')}</button></div></header><div className="content">{error && <p className="form-error page-error">{error}</p>}{loading ? <div className="loading">Loading your workspace…</div> : active === 'dashboard' ? <Dashboard tickets={filtered} onOpen={(id) => setModal({ type: 'ticket', id })} onCreate={() => setModal({ type: 'create' })} setActive={setActive}/> : <Board tickets={filtered} onOpen={(id) => setModal({ type: 'ticket', id })} onCreate={() => setModal({ type: 'create' })}/>}</div></main>{modal?.type === 'create' && <CreateModal users={users} onClose={() => setModal(null)} onCreated={refresh}/>} {modal?.type === 'ticket' && <TicketModal id={modal.id} user={auth.user} users={users} onClose={() => setModal(null)} onChanged={refresh}/>}</div>;
}
